#!/bin/bash
# Quick fix for "resource already exists" errors in AWS Learner Lab

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 AWS Learner Lab - Quick Fix"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 Problem: 'Resource already exists' errors"
echo ""
echo "✨ Solution: Use the new workflows!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 WORKFLOW OPTIONS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. 🚀 full-deployment"
echo "   → Deploy everything (infra + services)"
echo "   → Use for: Fresh start, complete deployment"
echo ""
echo "2. 🏗️  infrastructure-only"
echo "   → Deploy only AWS infrastructure"
echo "   → Use for: Testing infrastructure changes"
echo ""
echo "3. 🐳 services-only"
echo "   → Update Docker containers only"
echo "   → Use for: Code changes, quick updates"
echo ""
echo "4. 🗑️  destroy-infrastructure"
echo "   → Proper Terraform destroy"
echo "   → Falls back to cleanup script if no state"
echo "   → Use for: Clean shutdown"
echo ""
echo "5. 🧹 force-cleanup (NEW!)"
echo "   → Nuclear option, no state needed"
echo "   → Direct AWS API cleanup"
echo "   → Use for: When everything else fails"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚨 FIXING 'ALREADY EXISTS' ERRORS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step 1: Run workflow → force-cleanup"
echo "Step 2: Wait 3 minutes ⏳"
echo "Step 3: Run workflow → full-deployment"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "💡 HOW IT WORKS NOW:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ State saved AFTER deployment (for destroy)"
echo "✅ State restored ONLY for destroy"
echo "✅ Fresh deploys bypass cache (no conflicts)"
echo "✅ Auto-fallback if state missing"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📖 Full guide: AWS-LEARNER-LAB-GUIDE.md"
echo ""

